package cn.vcity.web.form;

import java.util.HashMap;
import java.util.Map;

import cn.vcity.model.VcityQuestion;
import cn.vcity.model.VcityQuestionitem;
import cn.vcity.wbase.common.base.BaseForm;

/**
 * generated by MyEclipse Persistence Tools
 */

public class VcityQuestionresultForm extends BaseForm {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    private Integer questionId;
    private Integer subTaskId;
    private Integer answerType;
    private String answerUser;
    private String answerTime;
    private Integer result;
    
    
	private Map questionMap = new HashMap();
	
	public Map getQuestionMap() {
		return questionMap;
	}

	public void setQuestionMap(Map questionMap) {
		this.questionMap = questionMap;
	}

	public VcityQuestion getQuestion(String key){
		if(getQuestionMap().get(key)==null){
			VcityQuestion vcityQuestion = new VcityQuestion();
			getQuestionMap().put(key, vcityQuestion);
			return vcityQuestion;
		}
		return (VcityQuestion)getQuestionMap().get(key);
	}
	
	public void setQuestion(String key, VcityQuestion vcityQuestion){
		getQuestionMap().put(key, vcityQuestion);
	}
	public Integer getQuestionId() {
		return questionId;
	}
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}
	public Integer getSubTaskId() {
		return subTaskId;
	}
	public void setSubTaskId(Integer subTaskId) {
		this.subTaskId = subTaskId;
	}
	public Integer getAnswerType() {
		return answerType;
	}
	public void setAnswerType(Integer answerType) {
		this.answerType = answerType;
	}
	public String getAnswerUser() {
		return answerUser;
	}
	public void setAnswerUser(String answerUser) {
		this.answerUser = answerUser;
	}
	public String getAnswerTime() {
		return answerTime;
	}
	public void setAnswerTime(String answerTime) {
		this.answerTime = answerTime;
	}
	public Integer getResult() {
		return result;
	}
	public void setResult(Integer result) {
		this.result = result;
	}
    
    
}