package cn.vcity.web.form;

import java.util.HashMap;
import java.util.Map;

import cn.vcity.model.VcityQuestion;
import cn.vcity.model.VcityQuestionitem;
import cn.vcity.wbase.common.base.BaseForm;

/**
 * generated by MyEclipse Persistence Tools
 */

public class VcityQuestionForm extends BaseForm {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer questionId;
    private Integer surveyId;
    private String questionName;
    private String questionDesc;
    private Integer questType;
    private Integer isTemplate = 0;
    private Integer questIndex = 0;
    private Integer itemLimit;
    
	private Map itemMap = new HashMap();
	
	public Map getItemMap() {
		return itemMap;
	}

	public void setItemMap(Map itemMap) {
		this.itemMap = itemMap;
	}

	public VcityQuestionitem getValue(String key){
		if(getItemMap().get(key)==null){
			VcityQuestionitem vcityQuestionitem = new VcityQuestionitem();
			getItemMap().put(key, vcityQuestionitem);
			return vcityQuestionitem;
		}
		return (VcityQuestionitem)getItemMap().get(key);
	}
	
	public void setValue(String key, VcityQuestionitem vcityQuestionitem){
		getItemMap().put(key, vcityQuestionitem);
	}
	
	private Map questionMap = new HashMap();
	
	public Map getQuestionMap() {
		return questionMap;
	}

	public void setQuestionMap(Map questionMap) {
		this.questionMap = questionMap;
	}

	public VcityQuestion getQuestion(String key){
		
		if(getQuestionMap().get(key)==null){
			VcityQuestion vcityQuestion = new VcityQuestion();
			getQuestionMap().put(key, vcityQuestion);
			return vcityQuestion;
		}
		return (VcityQuestion)getQuestionMap().get(key);
	}
	
	public void setQuestion(String key, VcityQuestion vcityQuestion){
		getQuestionMap().put(key, vcityQuestion);
	}
	
	/**
	 * @return the isTemplate
	 */
	public Integer getIsTemplate() {
		return isTemplate;
	}
	/**
	 * @param isTemplate the isTemplate to set
	 */
	public void setIsTemplate(Integer isTemplate) {
		this.isTemplate = isTemplate;
	}
	/**
	 * @return the itemLimit
	 */
	public Integer getItemLimit() {
		return itemLimit;
	}
	/**
	 * @param itemLimit the itemLimit to set
	 */
	public void setItemLimit(Integer itemLimit) {
		this.itemLimit = itemLimit;
	}
	/**
	 * @return the questIndex
	 */
	public Integer getQuestIndex() {
		return questIndex;
	}
	/**
	 * @param questIndex the questIndex to set
	 */
	public void setQuestIndex(Integer questIndex) {
		this.questIndex = questIndex;
	}
	/**
	 * @return the questionDesc
	 */
	public String getQuestionDesc() {
		return questionDesc;
	}
	/**
	 * @param questionDesc the questionDesc to set
	 */
	public void setQuestionDesc(String questionDesc) {
		this.questionDesc = questionDesc;
	}
	/**
	 * @return the questionId
	 */
	public Integer getQuestionId() {
		return questionId;
	}
	/**
	 * @param questionId the questionId to set
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}
	/**
	 * @return the questionName
	 */
	public String getQuestionName() {
		return questionName;
	}
	/**
	 * @param questionName the questionName to set
	 */
	public void setQuestionName(String questionName) {
		this.questionName = questionName;
	}
	/**
	 * @return the questType
	 */
	public Integer getQuestType() {
		return questType;
	}
	/**
	 * @param questType the questType to set
	 */
	public void setQuestType(Integer questType) {
		this.questType = questType;
	}
	/**
	 * @return the surveyId
	 */
	public Integer getSurveyId() {
		return surveyId;
	}
	/**
	 * @param surveyId the surveyId to set
	 */
	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}


}