package cn.vcity.web.form;

import cn.vcity.wbase.common.base.BaseForm;

/**
 * VcityResType generated by MyEclipse Persistence Tools
 */

public class VcityResTypeForm extends BaseForm {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2018887478795035796L;

	private Integer id;

	private String resType;

	private String resRemark;
	
	private Integer [] selectedRow;

	// Constructors

	public Integer[] getSelectedRow() {
		return selectedRow;
	}

	public void setSelectedRow(Integer[] selectedRow) {
		this.selectedRow = selectedRow;
	}

	/** default constructor */
	public VcityResTypeForm() {
	}

	/** full constructor */
	public VcityResTypeForm(String resType, String resRemark) {
		this.resType = resType;
		this.resRemark = resRemark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

	public String getResRemark() {
		return this.resRemark;
	}

	public void setResRemark(String resRemark) {
		this.resRemark = resRemark;
	}


}