package cn.vcity.web.form;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import cn.vcity.wbase.common.base.BaseForm;

/**
 * VcityResType generated by MyEclipse Persistence Tools
 */

public class VcitySureyForm extends BaseForm {
    private Integer sureyId;
    private String sureyName;
    private String sureyDesc;
    private String ceateTime =  new SimpleDateFormat("yyyy-MM-dd").format(new Date());
    private String createUser;
    private Integer credit;
    private Integer flag;
    
    private Integer [] selectedRow;

	// Constructors

	public Integer[] getSelectedRow() {
		return selectedRow;
	}

	public void setSelectedRow(Integer[] selectedRow) {
		this.selectedRow = selectedRow;
	}
	/**
	 * @return the ceateTime
	 */
	public String getCeateTime() {
		return ceateTime;
	}
	/**
	 * @param ceateTime the ceateTime to set
	 */
	public void setCeateTime(String ceateTime) {
		this.ceateTime = ceateTime;
	}
	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}
	/**
	 * @return the credit
	 */
	public Integer getCredit() {
		return credit;
	}
	/**
	 * @param credit the credit to set
	 */
	public void setCredit(Integer credit) {
		this.credit = credit;
	}
	/**
	 * @return the flag
	 */
	public Integer getFlag() {
		return flag;
	}
	/**
	 * @param flag the flag to set
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}
	/**
	 * @return the sureyDesc
	 */
	public String getSureyDesc() {
		return sureyDesc;
	}
	/**
	 * @param sureyDesc the sureyDesc to set
	 */
	public void setSureyDesc(String sureyDesc) {
		this.sureyDesc = sureyDesc;
	}
	/**
	 * @return the sureyId
	 */
	public Integer getSureyId() {
		return sureyId;
	}
	/**
	 * @param sureyId the sureyId to set
	 */
	public void setSureyId(Integer sureyId) {
		this.sureyId = sureyId;
	}
	/**
	 * @return the sureyName
	 */
	public String getSureyName() {
		return sureyName;
	}
	/**
	 * @param sureyName the sureyName to set
	 */
	public void setSureyName(String sureyName) {
		this.sureyName = sureyName;
	}

}