package cn.vcity.web.form;

import cn.vcity.model.VcityResource;
import cn.vcity.wbase.common.base.BaseForm;

/**
 * VcityResType generated by MyEclipse Persistence Tools
 */

public class VcityResCommonForm extends BaseForm {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2018887478795035796L;

	private int id;	//
	private int grade; 			//评价等级
	private String userName; 	//用户账号名
	private String createTime;  //评价时间
	private String ip; 			//评价IP
	private String common; 		//内容
	private VcityResource vcityResource;
	
	public String getCommon() {
		return common;
	}
	public void setCommon(String common) {
		this.common = common;
	}
	public String getCreateTime() {
		return createTime;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
	public int getGrade() {
		return grade;
	}
	public void setGrade(int grade) {
		this.grade = grade;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public VcityResource getVcityResource() {
		return vcityResource;
	}
	public void setVcityResource(VcityResource vcityResource) {
		this.vcityResource = vcityResource;
	}




}