package cn.vcity.model;

import java.util.Date;

/**
 * VcityManualchatinfo generated by MyEclipse Persistence Tools
 */

public class VcityManualchatinfo implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer taskId;
	private String chatTime;
	private String chatFrom;
	private String charTo;
	private String charInfo;
	private int isURL;
	
	private int chatFlag;

	// Constructors

	public int getChatFlag() {
		return chatFlag;
	}

	public void setChatFlag(int chatFlag) {
		this.chatFlag = chatFlag;
	}

	/** default constructor */
	public VcityManualchatinfo() {
	}

	/** full constructor */
	public VcityManualchatinfo(Integer taskId, String chatTime,
			String chatFrom, String charTo, String charInfo) {
		this.taskId = taskId;
		this.chatTime = chatTime;
		this.chatFrom = chatFrom;
		this.charTo = charTo;
		this.charInfo = charInfo;
	}
	
	public VcityManualchatinfo(Integer taskId, String chatTime,
			String chatFrom, String charTo, String charInfo, int chatFlag, int isURL) {
		this.taskId = taskId;
		this.chatTime = chatTime;
		this.chatFrom = chatFrom;
		this.charTo = charTo;
		this.charInfo = charInfo;
		this.chatFlag = chatFlag;
		this.isURL = isURL;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public String getChatTime() {
		return this.chatTime;
	}

	public void setChatTime(String chatTime) {
		this.chatTime = chatTime;
	}

	public String getChatFrom() {
		return this.chatFrom;
	}

	public void setChatFrom(String chatFrom) {
		this.chatFrom = chatFrom;
	}

	public String getCharTo() {
		return this.charTo;
	}

	public void setCharTo(String charTo) {
		this.charTo = charTo;
	}

	public String getCharInfo() {
		return this.charInfo;
	}

	public void setCharInfo(String charInfo) {
		this.charInfo = charInfo;
	}

	public int getIsURL() {
		return isURL;
	}

	public void setIsURL(int isURL) {
		this.isURL = isURL;
	}


}