package cn.vcity.model;

import java.util.HashSet;
import java.util.Set;

/**
 * VcityResType generated by MyEclipse Persistence Tools
 */

public class VcityResType implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2018887478795035796L;

	private Integer id;

	private String resType;

	private String resRemark;
	
	private Set vcityResource = new HashSet(0);

	// Constructors

	public Set getVcityResource() {
		return vcityResource;
	}

	public void setVcityResource(Set vcityResource) {
		this.vcityResource = vcityResource;
	}

	/** default constructor */
	public VcityResType() {
	}

	/** full constructor */
	public VcityResType(String resType, String resRemark) {
		this.resType = resType;
		this.resRemark = resRemark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

	public String getResRemark() {
		return this.resRemark;
	}

	public void setResRemark(String resRemark) {
		this.resRemark = resRemark;
	}

}