package cn.vcity.model;

/**
 * VcityChatuser generated by MyEclipse Persistence Tools
 */

public class VcityChatUser implements java.io.Serializable {

	// Fields

	private Integer id;
	private String username;
	private Integer lastUpdateTime;
	private VcityChatRoom vcityChatRoom = new VcityChatRoom();

	// Constructors

	public VcityChatUser(String username, Integer lastUpdateTime, VcityChatRoom vcityChatRoom) {
		super();
		this.username = username;
		this.lastUpdateTime = lastUpdateTime;
		this.vcityChatRoom = vcityChatRoom;
	}

	public VcityChatRoom getVcityChatRoom() {
		return vcityChatRoom;
	}

	public void setVcityChatRoom(VcityChatRoom vcityChatRoom) {
		this.vcityChatRoom = vcityChatRoom;
	}

	/** default constructor */
	public VcityChatUser() {
	}

	/** full constructor */
	public VcityChatUser(Integer id,String username,
			Integer lastUpdateTime) {
		this.id = id;
		this.username = username;
		this.lastUpdateTime = lastUpdateTime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

}