package cn.vcity.model;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;


/**
 * VcityQuestion generated by MyEclipse - Hibernate Tools
 */

public class VcityQuestion  implements java.io.Serializable {


    // Fields    

     private Integer questionId;
     private Integer surveyId;
     private String questionName;
     private String questionDesc;
     private Integer questType;
     private Integer isTemplate;
     private Integer questIndex;
     private Integer itemLimit;
     private Integer index;
     private VcitySurey vcitySurey = new VcitySurey();
     private Set<VcityQuestionitem> vcityQuestionitem = new HashSet<VcityQuestionitem>();


    // Constructors

    /** default constructor */
    public VcityQuestion() {
    }

    
    /** full constructor */
    public VcityQuestion(Integer surveyId, String questionName, String questionDesc, Integer questType, Integer isTemplate, Integer questIndex, Integer itemLimit) {
        this.surveyId = surveyId;
        this.questionName = questionName;
        this.questionDesc = questionDesc;
        this.questType = questType;
        this.isTemplate = isTemplate;
        this.questIndex = questIndex;
        this.itemLimit = itemLimit;
    }

   
    // Property accessors

    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    public Integer getSurveyId() {
        return this.surveyId;
    }
    
    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }

    public String getQuestionName() {
        return this.questionName;
    }
    
    public void setQuestionName(String questionName) {
        this.questionName = questionName;
    }

    public String getQuestionDesc() {
        return this.questionDesc;
    }
    
    public void setQuestionDesc(String questionDesc) {
        this.questionDesc = questionDesc;
    }

    public Integer getQuestType() {
        return this.questType;
    }
    
    public void setQuestType(Integer questType) {
        this.questType = questType;
    }

    public Integer getIsTemplate() {
        return this.isTemplate;
    }
    
    public void setIsTemplate(Integer isTemplate) {
        this.isTemplate = isTemplate;
    }

    public Integer getQuestIndex() {
        return this.questIndex;
    }
    
    public void setQuestIndex(Integer questIndex) {
        this.questIndex = questIndex;
    }

    public Integer getItemLimit() {
        return this.itemLimit;
    }
    
    public void setItemLimit(Integer itemLimit) {
        this.itemLimit = itemLimit;
    }

	/**
	 * @return the vcitySurey
	 */
	public VcitySurey getVcitySurey() {
		return vcitySurey;
	}


	/**
	 * @param vcitySurey the vcitySurey to set
	 */
	public void setVcitySurey(VcitySurey vcitySurey) {
		this.vcitySurey = vcitySurey;
	}


	/**
	 * @return the vcityQuestionitem
	 */
	public Set<VcityQuestionitem> getVcityQuestionitem() {
		return vcityQuestionitem;
	}


	/**
	 * @param vcityQuestionitem the vcityQuestionitem to set
	 */
	public void setVcityQuestionitem(Set<VcityQuestionitem> vcityQuestionitem) {
		this.vcityQuestionitem = vcityQuestionitem;
	}
   
	public void addVcityQuestionitem(VcityQuestionitem item){
		item.setVcityQuestion(this);
		getVcityQuestionitem().add(item);
	}
	
	public void addVcityQuestionitems(Map itemMap){
		Iterator iterator = itemMap.entrySet().iterator();
		Map.Entry entry;
		while (iterator.hasNext()) {
			entry = (Map.Entry)iterator.next();
			VcityQuestionitem item=(VcityQuestionitem)entry.getValue();
//			System.out.println("==>"+tt.getItemDesc());
			if(item.getItemDesc().length()>0){
				addVcityQuestionitem(item);	
			}
			//addVcityQuestionitem((VcityQuestionitem)entry.getValue());
		}
	}

	
	private Map itemMap = new HashMap();
	
	public Map getItemMap() {
		return itemMap;
	}

	public void setItemMap(Map itemMap) {
		this.itemMap = itemMap;
	}

	public VcityQuestionitem getItem(String key){
		if(getItemMap().get(key)==null){
			VcityQuestionitem vcityQuestionitem = new VcityQuestionitem();
			getItemMap().put(key, vcityQuestionitem);
			return vcityQuestionitem;
		}
		return (VcityQuestionitem)getItemMap().get(key);
	}
	
	public void setItem(String key, VcityQuestionitem vcityQuestionitem){
		getItemMap().put(key, vcityQuestionitem);
	}
	
	private Integer[] selectitemId;

	public Integer[] getSelectitemId() {
		return selectitemId;
	}
	public void setSelectitemId(Integer[] selectitemId) {
		this.selectitemId = selectitemId;
	}


	public Integer getIndex() {
		return index;
	}


	public void setIndex(Integer index) {
		this.index = index;
	}

}