package cn.vcity.model;

import java.util.HashSet;
import java.util.Set;

import cn.jsprun.domain.Scenetm;



/**
 * VcityChatRoom generated by MyEclipse Persistence Tools
 */

public class VcityChatRoom  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String roomName;
     private String describe;
     private String createdUser;
     private String beginTime;
     private String endTime;
     private Integer isPublish;  //0为未发布,1为已发布
     private Set<VcityChatUser> vcityChatUser = new HashSet<VcityChatUser>();


    // Constructors

    /** default constructor */
    public VcityChatRoom() {
    }

    
    /** full constructor */
    public VcityChatRoom(String roomName, String describe, String createdUser, String beginTime, String endTime) {
        this.roomName = roomName;
        this.describe = describe;
        this.createdUser = createdUser;
        this.beginTime = beginTime;
        this.endTime = endTime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIsPublish() {
		return isPublish;
	}


	public void setIsPublish(Integer isPublish) {
		this.isPublish = isPublish;
	}


	public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    public String getDescribe() {
        return this.describe;
    }
    
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getCreatedUser() {
        return this.createdUser;
    }
    
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    public String getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }


	public Set<VcityChatUser> getVcityChatUser() {
		return vcityChatUser;
	}


	public void setVcityChatUser(Set<VcityChatUser> vcityChatUser) {
		this.vcityChatUser = vcityChatUser;
	}
   
	public void addVcityChatUser(VcityChatUser child){
		child.setVcityChatRoom(this);
		getVcityChatUser().add(child);
	}






}