package cn.vcity.model;

import java.util.HashSet;
import java.util.Set;



/**
 * VcitySurey generated by MyEclipse - Hibernate Tools
 */

public class VcitySurey  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer sureyId;
     private String sureyName;
     private String sureyDesc;
     private String ceateTime;
     private String createUser;
     private Integer credit;
     private Integer flag;
     private Set<VcityQuestion> vcityQuestion = new HashSet<VcityQuestion>();


    // Constructors

    /** default constructor */
    public VcitySurey() {
    }
    
    public VcitySurey(Integer sureyId,String sureyName) {
    	this.sureyId = sureyId;
    	this.sureyName = sureyName;
    }
    
    public VcitySurey(Integer sureyId) {
		this.sureyId = sureyId;
	}

	/** full constructor */
    public VcitySurey(String sureyName, String sureyDesc, String ceateTime, String createUser, Integer credit, Integer flag) {
        this.sureyName = sureyName;
        this.sureyDesc = sureyDesc;
        this.ceateTime = ceateTime;
        this.createUser = createUser;
        this.credit = credit;
        this.flag = flag;
    }

   
    // Property accessors

    public Integer getSureyId() {
        return this.sureyId;
    }
    
    public void setSureyId(Integer sureyId) {
        this.sureyId = sureyId;
    }

    public String getSureyName() {
        return this.sureyName;
    }
    
    public void setSureyName(String sureyName) {
        this.sureyName = sureyName;
    }

    public String getSureyDesc() {
        return this.sureyDesc;
    }
    
    public void setSureyDesc(String sureyDesc) {
        this.sureyDesc = sureyDesc;
    }

    public String getCeateTime() {
        return this.ceateTime;
    }
    
    public void setCeateTime(String ceateTime) {
        this.ceateTime = ceateTime;
    }

    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

	/**
	 * @return the vcityQuestion
	 */
	public Set<VcityQuestion> getVcityQuestion() {
		return vcityQuestion;
	}


	/**
	 * @param vcityQuestion the vcityQuestion to set
	 */
	public void setVcityQuestion(Set<VcityQuestion> vcityQuestion) {
		this.vcityQuestion = vcityQuestion;
	}
   








}