package cn.vcity.model;



/**
 * VcityQuestionresult generated by MyEclipse - Hibernate Tools
 */

public class VcityQuestionresult  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer questionId;
     private Integer subTaskId;
     private Integer answerType;
     private String answerUser;
     private String answerTime;
     private Integer result;
     private VcityQuestionitem vcityQuestionitem = new VcityQuestionitem();


    // Constructors

    /** default constructor */
    public VcityQuestionresult() {
    }

    
    /** full constructor */
    public VcityQuestionresult(Integer questionId, Integer subTaskId, Integer answerType, String answerUser, String answerTime, Integer result) {
        this.questionId = questionId;
        this.subTaskId = subTaskId;
        this.answerType = answerType;
        this.answerUser = answerUser;
        this.answerTime = answerTime;
        this.result = result;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    public Integer getSubTaskId() {
        return this.subTaskId;
    }
    
    public void setSubTaskId(Integer subTaskId) {
        this.subTaskId = subTaskId;
    }

    public Integer getAnswerType() {
        return this.answerType;
    }
    
    public void setAnswerType(Integer answerType) {
        this.answerType = answerType;
    }

    public String getAnswerUser() {
        return this.answerUser;
    }
    
    public void setAnswerUser(String answerUser) {
        this.answerUser = answerUser;
    }

    public String getAnswerTime() {
        return this.answerTime;
    }
    
    public void setAnswerTime(String answerTime) {
        this.answerTime = answerTime;
    }

    public Integer getResult() {
        return this.result;
    }
    
    public void setResult(Integer result) {
        this.result = result;
    }


	public VcityQuestionitem getVcityQuestionitem() {
		return vcityQuestionitem;
	}


	public void setVcityQuestionitem(VcityQuestionitem vcityQuestionitem) {
		this.vcityQuestionitem = vcityQuestionitem;
	}
   








}