package cn.vcity.model;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;


/**
 * VcityResource generated by MyEclipse Persistence Tools
 */

public class VcityResource implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 8562882003538756487L;

	private Integer id;

	private String resName;        //资源名称

	private String resDesc;         //资源描述

	private Integer senceId;        //所属场景ID

	private Integer resType ;         //资源类型

	private String resImage;         //资源图片
	
	private String recommendImage;	 //	资源推荐图片

	private String moduleFileName;    //模型文件名

	private String resURL;           //资源URL

	private Integer isRecommend;       //是否推荐
	
	private VcityResType vcityResType;   //产品分类
	
	private String createUser;			//创建的User名
	
	private String createDate;			//创建的时间
	
	private Integer accessTotal;		//访问统计
	
	private Integer up;					//顶
	
	private Integer down;				//不顶
	
	public VcityResource(Integer id, String resName, String resDesc, Integer senceId, Integer resType, String resImage, String recommendImage, String moduleFileName, String resURL, Integer isRecommend, 
			 String createUser, String createDate) {
		super();
		this.id = id;
		this.resName = resName;
		this.resDesc = resDesc;
		this.senceId = senceId;
		this.resType = resType;
		this.resImage = resImage;
		this.recommendImage = recommendImage;
		this.moduleFileName = moduleFileName;
		this.resURL = resURL;
		this.isRecommend = isRecommend;
		//this.vcityResType = vcityResType;
		this.createUser = createUser;
		this.createDate = createDate;
	}



	/** default constructor */
	public VcityResource() {
	}

	public VcityResource(Integer id, String resName, String resImage, String resURL){
		this.id = id;
		this.resName = resName;
		this.resImage = resImage;
		this.resURL = resURL;
	}

	public VcityResource(Integer id) {
		this.id = id;
	}



	public VcityResource(Integer id, String resName, String resDesc, Integer senceId, 
			Integer resType, String resImage,String recommendImage, String moduleFileName, String resURL,
			Integer isRecommend, VcityResType vcityResType) {
		super();
		this.id = id;
		this.resName = resName;
		this.resDesc = resDesc;
		this.senceId = senceId;
		this.resType = resType;
		this.resImage = resImage;
		this.recommendImage= recommendImage;
		this.moduleFileName = moduleFileName;
		this.resURL = resURL;
		this.isRecommend = isRecommend;
		this.vcityResType = vcityResType;
	}



	public VcityResource(Integer id, String resName, String resDesc, Integer senceId, Integer resType,
			String resImage,String recommendImage, String moduleFileName, String resURL, 
			Integer isRecommend, Integer accessTotal) {
		super();
		this.id = id;
		this.resName = resName;
		this.resDesc = resDesc;
		this.senceId = senceId;
		this.resType = resType;
		this.resImage = resImage;
		this.recommendImage= recommendImage;
		this.moduleFileName = moduleFileName;
		this.resURL = resURL;
		this.isRecommend = isRecommend;
		this.accessTotal = accessTotal;
	}
	public VcityResource(Integer id, String resName, String resDesc, Integer senceId,
			Integer resType, String resImage,String recommendImage, String moduleFileName, String resURL, 
			Integer isRecommend,VcityResType vcityResType, Integer accessTotal,Integer up,Integer down) {
		super();
		this.id = id;
		this.resName = resName;
		this.resDesc = resDesc;
		this.senceId = senceId;
		this.resType = resType;
		this.resImage = resImage;
		this.recommendImage=recommendImage;
		this.moduleFileName = moduleFileName;
		this.resURL = resURL;
		this.isRecommend = isRecommend;
		this.vcityResType = vcityResType;
		this.accessTotal = accessTotal;
		this.up=up;
		this.down=down;
	}

	public VcityResource(Integer id, String resName, String resDesc, Integer senceId,
			Integer resType, String resImage, String moduleFileName, String resURL, 
			Integer isRecommend,VcityResType vcityResType, Integer accessTotal,Integer up,Integer down) {
		super();
		this.id = id;
		this.resName = resName;
		this.resDesc = resDesc;
		this.senceId = senceId;
		this.resType = resType;
		this.resImage = resImage;
		this.moduleFileName = moduleFileName;
		this.resURL = resURL;
		this.isRecommend = isRecommend;
		this.vcityResType = vcityResType;
		this.accessTotal = accessTotal;
		this.up=up;
		this.down=down;
	}
	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public Integer getIsRecommend() {
		return isRecommend;
	}


	public void setIsRecommend(Integer isRecommend) {
		this.isRecommend = isRecommend;
	}


	public String getModuleFileName() {
		return moduleFileName;
	}


	public void setModuleFileName(String moduleFileName) {
		this.moduleFileName = moduleFileName;
	}


	public String getResDesc() {
		return resDesc;
	}


	public void setResDesc(String resDesc) {
		this.resDesc = resDesc;
	}


	public String getResImage() {
		return resImage;
	}

	

	public void setResImage(String resImage) {
		this.resImage = resImage;
	}


	public String getResName() {
		return resName;
	}


	public void setResName(String resName) {
		this.resName = resName;
	}


	public Integer getResType() {
		return resType;
	}


	public void setResType(Integer resType) {
		this.resType = resType;
	}


	public String getResURL() {
		return resURL;
	}


	public void setResURL(String resURL) {
		this.resURL = resURL;
	}


	public Integer getSenceId() {
		return senceId;
	}


	public void setSenceId(Integer senceId) {
		this.senceId = senceId;
	}


	public VcityResType getVcityResType() {
		return vcityResType;
	}


	public void setVcityResType(VcityResType vcityResType) {
		this.vcityResType = vcityResType;
	}



	public String getCreateDate() {
		return createDate;
	}



	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}



	public String getCreateUser() {
		return createUser;
	}



	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}



	public Integer getAccessTotal() {
		return accessTotal;
	}



	public void setAccessTotal(Integer accessTotal) {
		this.accessTotal = accessTotal;
	}



	public Integer getDown() {
		return down;
	}



	public void setDown(Integer down) {
		this.down = down;
	}



	public Integer getUp() {
		return up;
	}



	public void setUp(Integer up) {
		this.up = up;
	}

	public void setRecommendImage(String recommendImage) {
		this.recommendImage = recommendImage;
	}
	
	public String getRecommendImage(){
		return recommendImage;		
	}


	public String getFullImage(){
		if (this.resType==1) {
			return "uploadfile/VCity/Application/image/"+resImage;
		} else {
			return "uploadfile/VCity/Model/image/"+resImage;
		}		
	}
	
	public String getViewRecommendImage(){
		 return "uploadfile/VCity/Recommend/image/"+this.recommendImage;
	}
	
	public String getViewAppFileName(){
		return "uploadfile/VCity/Application/software/"+this.moduleFileName;
	}
	
	public String getViewSkinFileName(){
		return "uploadfile/VCity/Model/Wingo/"+this.moduleFileName;
	}
	
	public String getDownFileName(){
		if (this.resType==1) {
			return "uploadfile/VCity/Application/software/"+this.moduleFileName;
		} else {
			return "uploadfile/VCity/Model/Wingo/"+this.moduleFileName;
		}
	}
	
	public String getSkinDirectory(){
		if (this.resType==2) {
			String name = this.moduleFileName;
			name = name.substring(0,name.lastIndexOf("."));
			return "uploadfile/VCity/Model/Wingo/"+name;
		} else {
			return null;
		}
	}

}