package cn.vcity.model;

/**
 * VcityChatroominfo generated by MyEclipse Persistence Tools
 */

public class VcityChatRoominfo implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer roomId;

	private String chatTime;

	private String chatFrom;

	private String chatTo;

	private String chatInfo;

	// Constructors

	/** default constructor */
	public VcityChatRoominfo() {
	}

	/** full constructor */
	public VcityChatRoominfo(Integer roomId, String chatTime, String chatFrom,
			String chatTo, String chatInfo) {
		this.roomId = roomId;
		this.chatTime = chatTime;
		this.chatFrom = chatFrom;
		this.chatTo = chatTo;
		this.chatInfo = chatInfo;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public String getChatTime() {
		return this.chatTime;
	}

	public void setChatTime(String chatTime) {
		this.chatTime = chatTime;
	}

	public String getChatFrom() {
		return this.chatFrom;
	}

	public void setChatFrom(String chatFrom) {
		this.chatFrom = chatFrom;
	}

	public String getChatTo() {
		return this.chatTo;
	}

	public void setChatTo(String chatTo) {
		this.chatTo = chatTo;
	}

	public String getChatInfo() {
		return this.chatInfo;
	}

	public void setChatInfo(String chatInfo) {
		this.chatInfo = chatInfo;
	}

}